chain:
    bech32_prefix: ovg
    modules:
#        - actions
        - auth
        - bank
#        - consensus
        - gov
        - messages
        - mint
        - modules
        - slashing
#        - staking
        - overgold

node:
    type: remote
    config:
        rpc:
            client_name: juno
            address: http://localhost:26657
            max_connections: 1
        grpc:
            address: http://localhost:9090
            insecure: true

parsing:
    workers: 1
    listen_new_blocks: true
    parse_old_blocks: true
    parse_genesis: true
    start_height: 1
    average_block_time: 3s

database:
    url: postgresql://postgres:postgres@localhost:5432/juno?sslmode=disable&search_path=public
    max_open_connections: 10
    max_idle_connections: 10
    # How many blocks for each partition.
    # In this example partition is created per 100,000 blocks.
    partition_size: 100000
    # How many rows of transactions are migrated per batch
    partition_batch: 1000

logging:
    level: debug
    format: text

actions: # used by hasura
    port: 80
    node:
        rpc:
            address: http://localhost:26657
        grpc:
            address: http://localhost:9090
            insecure: true
