name: Tests
# Tests / Code Coverage workflow runs unit tests and uploads a code coverage report.
# This workflow is run on pushes to master & every Pull Requests where a .go, .mod, .sum have been changed.
on:
  pull_request:
  push:
    branches:
      - chains/*
      - cosmos/*

jobs:
  Cleanup-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    if: "!startsWith(github.ref, 'refs/tags/') && !startsWith(github.ref, 'refs/tags/cosmos')"

  Unit-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Go ğŸ§°
        uses: actions/setup-go@v5
        with:
          go-version: "1.20"

      - name: Compute diff ğŸ“œ
        uses: technote-space/get-diff-action@v6.1.2
        id: git_diff
        with:
          SUFFIX_FILTER: |
            .go
            .mod
            .sum

      - name: Build ğŸ”¨
        if: "env.GIT_DIFF != ''"
        run: make build

      - name: Test & Coverage report creation ğŸ§ª
        run: make test-unit stop-docker-test

      - name: Upload coverage ğŸ“¤
        if: "env.GIT_DIFF != ''"
        uses: codecov/codecov-action@v4.0.1
        with:
          file: ./coverage.txt
